### ISSUE TITLE
Not compatible with newer versions of OpenSSL

### ISSUE THREAD

**Issue by engerim42** [AndrianBdn/aes-command-line#1]
If you decrypt a file with OpenSSL 1.1.1 that was encoded with 1.0.2g:

```
enter aes-256-cbc decryption password:
*** WARNING : deprecated key derivation used.
Using -iter or -pbkdf2 would be better.
bad decrypt
139936583193024:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:../crypto/evp/evp_enc.c:537:
```

Due to option changes of OpenSSL. MD5 is no longer the default hashing algorithm. Adding "-md md5" if you have an old file fixes this. Adding "-md sha256" Should make it compatible for both versions but that hashing algorithm is no longer considered secure!

Also the "shebang" is "#/bin/sh" but in fact its a bash script so they should have "/bin/bash"

**Comment by AndrianBdn** [comment]
Thank you for your report. Indeed there is a number of problems with hashing in OpenSSL and OpenSSL forks. 

After investigating all of this, I think the best decision would be to deprecate the entire thing. 

I still fixed shebang (you are right — these are bash scripts) and added "-md md5" for compatibility with older encrypted files. 

I've put 'Deprecation Notice' in README.md. I suggest to re-encrypt your files with another tool. While I haven't done security review myself, the following implementation seems promising: https://github.com/FiloSottile/age
